version: "3.7"
services:
  main:
    container_name: georg-hoechstgan
    build:
      context: .
      dockerfile: "Dockerfile"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: 1
              device_ids: [ "0", "1", "2", "3", "4", "5", "6", "7" ]
              capabilities: [ gpu ]
    ports:
      - "8888:8888"
      - "9999:9999"
    shm_size: "16gb"
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - "~/hoechstgan:/app"
      - "/mnt/isilon1/georg/hoechstgan:/data"
