#!/bin/bash

set -e

if [ "$1" == "0" ]; then
    RUNS="1tbxka4t h07uj4ba 3qgx0z2j 3i72093a"
    GPUS="0"
elif [ "$1" = "1" ]; then
    RUNS="1stvzk95 2oyckvb6 1i08jpkk"
    GPUS="1"
else
    echo "Supply argument!"
fi

echo "RUNS: $RUNS"
echo "GPUS: $GPUS"

for run in $RUNS; do
    poetry run python test.py $run --gpus=$GPUS --size 100000
done